version: 2.1
defaults: &defaults
  docker:
      - image: circleci/node:13.8.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          - key: {{ npm_packages }}
          - path: /node_modules
      - run: npm run build
  test:
    <<: *defaults
    steps:
      - store_cache:
        - key: {{ npm_packages }}
      - run:
        - npm i
        - npm run test
  analyze:
    <<: *defaults
    steps:
      - store_cache:
        - key: {{ npm_packages }}
      - run: npm audit
workflows:
  build-test-analyze:
    - build
    - test:
        requires:
          - build
    - analyze:
        requires:
          - test
